#!syntax bash
alias ,s='. ~/.bashrc' # Source bashrc
alias ,c='$EDITOR $HOME/.bashrc' # Edit bashrc

# Environment
export TERMINAL=/usr/local/bin/st
export EDITOR=/usr/bin/nvim
export BROWSER=firefox

export ARCH=$(uname -m)
export TERM_COLORS="$(tput colors)"
export GPG_TTY=`tty`
export DVTM_TERM=st

export LUA_PATH="$HOME/git/lua-libs/?.lua;;"
export PYTHONPATH="$HOME/git/python-libs"
# Bash configuration

    #Git Prompt
    . $HOME/.config/git-prompt.sh
    GIT_PS1_DESCRIBE_STYLE='contains'
    GIT_PS1_SHOWCOLORHINTS='y'
    GIT_PS1_SHOWDIRTYSTATE='y'
    GIT_PS1_SHOWSTASHSTATE='y'
    GIT_PS1_SHOWUNTRACKEDFILES='y'
    GIT_PS1_SHOWUPSTREAM='auto'

    #Prompt
    GREEN="\033[38;5;34m"
    YELLOW="\033[38;5;3m"
    CLEAR="\033[0m"
    export PS1="\[$GREEN\]\u\[$CLEAR\]\[$YELLOW\]@\[$CLEAR\]\h \[$CLEAR\]\[$YELLOW\]\w\[$CLEAR\]\$(__git_ps1) \$ "

	# Autocd when typing path
	shopt -s autocd

	# Vi-mode
	set -o vi

	# HISTFILE=~/.config/bash/history

# Load source files
export BASH_FOLDER="$HOME/.config/bash"

if [ -d $BASH_FOLDER ] ; then
	for f in $BASH_FOLDER/* ; do
	source "$f"
	done
	unset f
fi

if [ -f /usr/share/nnn/quitcd/quitcd.bash_zsh ]; then
    source /usr/share/nnn/quitcd/quitcd.bash_zsh
fi
