#!/bin/bash

alias ,f="$EDITOR $BASH_FOLDER/*-functions"

isexec () { hash "$@" 2> /dev/null; }

vifm()
{
	local dst="$(command vifm --choose-dir - "$@")"
	if [ -z "$dst" ]; then
		echo 'Directory picking cancelled/failed'
		return 1
	fi
	cd "$dst"
}

mkcdir () {
	mkdir -p -- "$1"
	cd -P -- "$1"
}

where () {
	hash "$@" 2> /dev/null
	hash -t "$@" 2> /dev/null
}
